// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: drones/state.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drones_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_drones_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_drones_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drone *Drone `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drones_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_drones_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_drones_state_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetDrone() *Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

type Drone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos            *Vec2   `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Angle          float32 `protobuf:"fixed32,2,opt,name=angle,proto3" json:"angle,omitempty"`
	NextCheckpoint int32   `protobuf:"varint,3,opt,name=nextCheckpoint,proto3" json:"nextCheckpoint,omitempty"`
}

func (x *Drone) Reset() {
	*x = Drone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drones_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_drones_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_drones_state_proto_rawDescGZIP(), []int{2}
}

func (x *Drone) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Drone) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Drone) GetNextCheckpoint() int32 {
	if x != nil {
		return x.NextCheckpoint
	}
	return 0
}

type Vec2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drones_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_drones_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_drones_state_proto_rawDescGZIP(), []int{3}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_drones_state_proto protoreflect.FileDescriptor

var file_drones_state_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22,
	0x2d, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x72, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65,
	0x73, 0x2e, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x22, 0x65,
	0x0a, 0x05, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x56, 0x65,
	0x63, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x32, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drones_state_proto_rawDescOnce sync.Once
	file_drones_state_proto_rawDescData = file_drones_state_proto_rawDesc
)

func file_drones_state_proto_rawDescGZIP() []byte {
	file_drones_state_proto_rawDescOnce.Do(func() {
		file_drones_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_drones_state_proto_rawDescData)
	})
	return file_drones_state_proto_rawDescData
}

var file_drones_state_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_drones_state_proto_goTypes = []interface{}{
	(*State)(nil),  // 0: drones.State
	(*Player)(nil), // 1: drones.Player
	(*Drone)(nil),  // 2: drones.Drone
	(*Vec2)(nil),   // 3: drones.Vec2
}
var file_drones_state_proto_depIdxs = []int32{
	1, // 0: drones.State.players:type_name -> drones.Player
	2, // 1: drones.Player.drone:type_name -> drones.Drone
	3, // 2: drones.Drone.pos:type_name -> drones.Vec2
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_drones_state_proto_init() }
func file_drones_state_proto_init() {
	if File_drones_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drones_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drones_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drones_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drones_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drones_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drones_state_proto_goTypes,
		DependencyIndexes: file_drones_state_proto_depIdxs,
		MessageInfos:      file_drones_state_proto_msgTypes,
	}.Build()
	File_drones_state_proto = out.File
	file_drones_state_proto_rawDesc = nil
	file_drones_state_proto_goTypes = nil
	file_drones_state_proto_depIdxs = nil
}
